from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('',views.home, name="home"),
    path('signup',views.signup, name="signup"),
    path('signin',views.signin, name="signin"),
    path('secpg',views.secpg, name="secpg"),
    path('iitname',views.iitname, name="iitname"),
    path('iitname2',views.iitname2, name="iitname2"),
    path('staname',views.staname, name="staname"),
    path('staname2',views.staname2, name="staname2"),
    path('IITJ',views.IITJ, name="IITJ"),
    path('IITBhil',views.IITBhil, name="IITBhil"),
    path('IITBBS',views.IITBBS, name="IITBBS"),
    path('IITB',views.IITB, name="IITB"),
    path('IITD',views.IITD, name="IITD"),
    path('IITDh',views.IITDh, name="IITDh"),
    path('IITDw',views.IITDw, name="IITDw"),
    path('IITGn',views.IITGn, name="IITGn"),
    path('IITGo',views.IITGo, name="IITGo"),
    path('IITG',views.IITG, name="IITG"),
    path('IITH',views.IITH, name="IITH"),
    path('IITI',views.IITI, name="IITI"),
    path('IITJm',views.IITJm, name="IITJm"),
    path('IITK',views.IITK, name="IITK"),
    path('IITKh',views.IITKh, name="IITKh"),
    path('IITM',views.IITM, name="IITM"),
    path('IITMn',views.IITMn, name="IITMn"),
    path('IITP',views.IITP, name="IITP"),
    path('IITPn',views.IITPn, name="IITPn"),
    path('IITR',views.IITR, name="IITR"),
    path('IITRo',views.IITRo, name="IITRo"),
    path('IITT',views.IITT, name="IITT"),
    path('IITV',views.IITV, name="IITV"),
]